---

- name: Create application user
  user:
    name: myapp

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/myapp.conf
  notify: restart nginx

- name: Ensure application directory is present
  file: path=/var/www/myapp state=directory mode=0755

- name: Copy app to working directory
  template: src=index.php.j2 dest=/var/www/myapp/index.php
  notify: restart nginx

- name: Copy php-fpm configuration
  template: src=phpfpm.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm